/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bob_trainservice_util_JavaJniTrain */

#ifndef _Included_com_bob_trainservice_util_JavaJniTrain
#define _Included_com_bob_trainservice_util_JavaJniTrain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bob_trainservice_util_JavaJniTrain
 * Method:    getStringForC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bob_trainservice_util_JavaJniTrain_getStringForC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
